package view.com.raven.form;

import javax.swing.ImageIcon;
import view.com.raven.model.Model_Card;

public class Form_Vendas extends javax.swing.JPanel {
    
    public Form_Vendas() {
         initComponents();
         cardSales1.setData(new Model_Card(new ImageIcon(getClass().getResource("/com/raven/icon/stock.png")), "Stock Total", "$200000", "Increased by 60%"));
    }

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardSales1 = new view.com.raven.component.CardSales();

        setBackground(new java.awt.Color(242, 238, 238));
        setLayout(null);

        cardSales1.setColor1(new java.awt.Color(142, 142, 250));
        cardSales1.setColor2(new java.awt.Color(123, 123, 245));
        add(cardSales1);
        cardSales1.setBounds(0, 0, 1036, 465);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.com.raven.component.CardSales cardSales1;
    // End of variables declaration//GEN-END:variables
}
