/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.com.raven.form;

import javax.swing.ImageIcon;
import view.com.raven.model.Model_Card;

/**
 *
 * @author Matheus
 */
public class Form_Funcionarios extends javax.swing.JPanel {

    public Form_Funcionarios() {
        initComponents();
        cardEmployees1.setData(new Model_Card(new ImageIcon(getClass().getResource("/com/raven/icon/stock.png")), "Stock Total", "$200000", "Increased by 60%"));
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cardEmployees1 = new view.com.raven.component.CardEmployees();

        setBackground(new java.awt.Color(242, 238, 238));

        cardEmployees1.setColor1(new java.awt.Color(142, 142, 250));
        cardEmployees1.setColor2(new java.awt.Color(123, 123, 245));
        cardEmployees1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardEmployees1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(cardEmployees1, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cardEmployees1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cardEmployees1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardEmployees1MouseClicked
       
    }//GEN-LAST:event_cardEmployees1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.com.raven.component.CardEmployees cardEmployees1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
