package view.com.raven.form;

import com.estoque.banco.ConexaoBD;
import com.estoque.controller.ControllerFuncionario;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import view.com.raven.swing.Table;

public class Form_Vendas extends javax.swing.JPanel {

    ConexaoBD con = new ConexaoBD();

    ControllerFuncionario controllerFuncionario = new ControllerFuncionario();
    
    public Form_Vendas() {
        initComponents();
        desabilitarCampos();
        desabilitarBotao();
        con.getConectar();
        //carregarTabelaFuncionarios("call sp_list_funcionarios()");
    }

    public void limparCampos() {
    }

    public final void desabilitarCampos() {
    }

    public void habilitarCampos() {
    }

    public final void desabilitarBotao() {
    /*    btnAlterar.setEnabled(false);
        btnNovo.setEnabled(true);
        btnBuscarCep.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnRemover.setEnabled(false);
        btnSalvar.setEnabled(false);*/
    }

    public void habilitarBotao() {
        /*btnAlterar.setEnabled(true);
        btnBuscarCep.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnNovo.setEnabled(false);
        btnRemover.setEnabled(true);
        btnSalvar.setEnabled(true);*/
    }

    
    /**
     * carregar tabela clientes
     *
     * @param Sql
     */

    /**public void carregarTabelaFuncionarios(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Nome", "Data Nascimento", "RG", "CPF", "Login", "Fone", "Email", "Cargo"};
        con.getConectar();
        con.executarSql(Sql);

        try {
            con.getResultSet().first();
            do {
                dados.add(new Object[]{con.getResultSet().getString("nome"), con.getResultSet().getString("dt_nascimento"),
                    con.getResultSet().getString("rg"), con.getResultSet().getString("cpf"), con.getResultSet().getString("login"),
                    con.getResultSet().getString("fone"), con.getResultSet().getString("email"), con.getResultSet().getString("cargo")});
            } while (con.getResultSet().next());
        } catch (SQLException e) {
//            JOptionPane.showMessageDialog(null, "Busque Novamente");
        }
        TabelaFuncionarios tabelafuncionarios = new TabelaFuncionarios(dados, colunas);
        table_Funcionarios.setModel(tabelafuncionarios);
        table_Funcionarios.getColumnModel().getColumn(0).setPreferredWidth(160);
        table_Funcionarios.getColumnModel().getColumn(0).setResizable(false);
        table_Funcionarios.getColumnModel().getColumn(1).setPreferredWidth(110);
        table_Funcionarios.getColumnModel().getColumn(1).setResizable(false);
        table_Funcionarios.getColumnModel().getColumn(2).setPreferredWidth(80);
        table_Funcionarios.getColumnModel().getColumn(2).setResizable(false);
        table_Funcionarios.getColumnModel().getColumn(3).setPreferredWidth(100);
        table_Funcionarios.getColumnModel().getColumn(3).setResizable(false);
        table_Funcionarios.getColumnModel().getColumn(4).setPreferredWidth(130);
        table_Funcionarios.getColumnModel().getColumn(4).setResizable(false);
        table_Funcionarios.getColumnModel().getColumn(5).setPreferredWidth(130);
        table_Funcionarios.getColumnModel().getColumn(5).setResizable(false);
        table_Funcionarios.getColumnModel().getColumn(6).setPreferredWidth(160);
        table_Funcionarios.getColumnModel().getColumn(6).setResizable(false);
        table_Funcionarios.getColumnModel().getColumn(7).setPreferredWidth(100);
        table_Funcionarios.getColumnModel().getColumn(7).setResizable(false);

        table_Funcionarios.getTableHeader().setReorderingAllowed(false);
        table_Funcionarios.setAutoResizeMode(table_Funcionarios.AUTO_RESIZE_OFF);
        table_Funcionarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(242, 238, 238));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 987, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
