/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.com.raven.main;

//import com.raven.event.EventMenuSelected;
import com.estoque.banco.ConexaoBD;
import view.com.raven.form.Form_Home;
import view.com.raven.form.Form_Product;
import view.com.raven.form.Form_Vendas;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import view.com.raven.event.EventMenuSelected;
import java.sql.Timestamp;
import view.com.raven.form.Form_Funcionarios;
import view.com.raven.form.Form_Pagamento;
import view.com.raven.form.Form_CodigoBarras;
import view.com.raven.form.Form_Historico;

/**
 *
 * @author RAVEN
 */
public class Main extends javax.swing.JFrame {

    private Form_Home home;
    private final Form_Product formProduct;
    private Form_Funcionarios formFuncionarios;
    private Form_Vendas formVendas;
    private final Form_Pagamento formPagamento;
    private Form_Historico form_Historico;
    private Form_CodigoBarras form_CodigoBarras;
    int codUser;

    public String usuário;

    ConexaoBD con = new ConexaoBD();

    public Main() {
        initComponents();
        con.getConectar();
        setBackground(new Color(0, 0, 0, 0));
        home = new Form_Home();
        formProduct = new Form_Product();
        formFuncionarios = new Form_Funcionarios();
        formVendas = new Form_Vendas();
        formPagamento = new Form_Pagamento();
        form_Historico = new Form_Historico();
        form_CodigoBarras = new Form_CodigoBarras();
        menu1.initMoving(Main.this);

        menu1.addEventMenuSelected(new EventMenuSelected() {
            @Override
            public void selected(int index) {
                switch (index) {
                    case 0:
                        setForm(home);
                        break;
                    case 1:
                        setForm(formFuncionarios);
                        break;
                    case 2:
                        CheckLogin();
                        break;
                    case 3:
                        setForm(form_CodigoBarras);
                        break;
                    case 6:
                        setForm(formVendas);
                        break;
                    case 7:
                        setForm(form_Historico);
                        break;
                    case 8:
                        setForm(home);
                        break;
                    default:
                        break;
                }
            }
        });

        //  set when system open start with home form
        setForm(new Form_Home());
    }

    private void CheckLogin() {
        try {
            Form_Product FormularioProdutos = new Form_Product();
            con.executarSql("select*from tb_user where login='" + lbusuarios.getText() + "'");
            con.getResultSet().first();
            if (con.getResultSet().getString("perfil").equals("Administrador")) {
                if (FormularioProdutos == FormularioProdutos) {
                    setForm(FormularioProdutos);
                    FormularioProdutos.setVisible(true);
                } else {
                    FormularioProdutos.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Você não tem Acesso a essa Funcionalidade!\n Contate o Administrador do Sistema!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Você não tem Acesso a essa Funcionalidade!\n Contate o Administrador do Sistema!" + ex.getMessage());
        }
    }

    private void salvarUserLogsExit() {

        con.getConectar();
        try {
            con.executarSql("select*from tb_userslogs where login='" + lbusuarios.getText() + "'");
            con.getResultSet().last();
            codUser = con.getResultSet().getInt("id");

            PreparedStatement pst = con.con.prepareStatement("UPDATE tb_userslogs SET registration_date_update = CURRENT_TIMESTAMP WHERE id=?");

            pst.setInt(1, codUser);
            pst.execute();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro no update" + e);

        }

    }

    private void setForm(JComponent com) {
        mainPanel.removeAll();
        mainPanel.add(com);
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new view.com.raven.swing.PanelBorder();
        header2 = new view.com.raven.component.Header();
        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbusuarios = new javax.swing.JLabel();
        btn_sair = new javax.swing.JButton();
        menu1 = new view.com.raven.component.Menu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        panelBorder1.setBackground(new java.awt.Color(242, 238, 238));

        header2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        mainPanel.setOpaque(false);
        mainPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Usuário:");

        btn_sair.setText("sair");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addGap(20, 20, 20)
                        .addComponent(lbusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btn_sair))
                    .addComponent(header2, javax.swing.GroupLayout.PREFERRED_SIZE, 1095, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1095, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addComponent(header2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbusuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                    .addComponent(btn_sair))
                .addContainerGap(18, Short.MAX_VALUE))
            .addComponent(menu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        salvarUserLogsExit();
        System.exit(0);
        con.getfecharConexao();
    }//GEN-LAST:event_btn_sairActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        lbusuarios.setText(usuário);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Long datetime = System.currentTimeMillis();
        Timestamp timestamp = new Timestamp(datetime);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sair;
    private view.com.raven.component.Header header2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbusuarios;
    private javax.swing.JPanel mainPanel;
    private view.com.raven.component.Menu menu1;
    private view.com.raven.swing.PanelBorder panelBorder1;
    // End of variables declaration//GEN-END:variables
}
